### ISSUE TITLE
chiffre = Erreur de lexeur

### ISSUE THREAD

**Issue by pastjean** [mlarouche/QPainterDebugger#1]
Je pense que si une variable ou fonction commence par un chiffre sa plante.

ie:

1234eeee 

le lexer va commencer a l'interprété en chiffre et après va interprété "eeee" sans se pleindre
tu va avoir 2 token 1234 et eeee ... a moins que ce soit un comportement voulu

**Comment by mlarouche** [comment]
A date je dirais que c'est voulu. Le parseur catche l'erreur entk
